version: "3"
services:
  app:
    container_name: app
    image: certificates
    ports:
      - 8080:8080
    depends_on:
      - postgres
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PASSWORD: postgres

  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: clevertec
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres